### ISSUE TITLE
When I add handleSelector class all the instances resize at the same time.

### ISSUE THREAD

**Issue by zardaloop** [RickStrahl/jquery-resizable#1]
I have couple of element on the page which I am using the same class for their handler which is  handleSelector: '.win-size-grip' as you had in your example. Is there anyway that the resize only applies to the handler within a div or textarea but not others?

**Comment by RickStrahl** [comment]
You have to use a selector that specifically matches that element or element group. If you mark the `<div>` with a custom class or an #id you can do use:

```javascript
$(el).resizable( { handleSelector: "#MyDiv .win-size-grip" } )
```

The resizing should only affect the element that's being resized though regardless of whether they are all selected.
