### ISSUE TITLE
[Feature Request] Add support to multiple module loaders

### ISSUE THREAD

**Issue by thiagodp** [RickStrahl/jquery-resizable#14]
I tried to use `jquery-resizable` with `node.js` but it does not recognize `jQuery` as a *global* insize `jquery-resizable` (because it uses the *CommonJS* approach to include a dependency).

Since that *CommonJS* and *AMD* include dependencies in a different way, I adapted `jquery-resizable` to work with them and [created a pull request](https://github.com/RickStrahl/jquery-resizable/pull/13).

**Comment by RickStrahl** [comment]
Thanks for the PR  d8ebdf2.
