### ISSUE TITLE
Resizable stops working if you load Jquery-UI 1.11.4

### ISSUE THREAD

**Issue by brapion** [RickStrahl/jquery-resizable#17]
colResizable-1.6.min.js works fine until I load the jquery-ui 1.11.4

Should it be compatible?

**Comment by davidmcglynn** [comment]
Agreed - ran into this as well - even with the latest 1.12.1

**Comment by brapion** [comment]
Thanks David, that fix worked a treat. Hopefully Rick will consider making the change in the next version release.

**Comment by gquach** [comment]
I experienced this namespace collision problem as well. Would be good to permanently rename the 'resizable' function call, especially since some web apps load jQuery UI by default and it's not always easy to turn it off.
