### ISSUE TITLE
Suggestion to extend handleSelector syntax

### ISSUE THREAD

**Issue by Slowlearneruk** [RickStrahl/jquery-resizable#19]
I had some difficulty getting this plugin to work with a use case very similar to your example but where I had many selectors added with a jade mixin that did not have unique names:
```
.split
	.split-top
		p Top content
	.split-thumb
	.split-bottom
		p Bottom content
```
The simple approach was attaching the same move events to all of the `.split-thumb` members:
```
$('.split-top').resizable({
	handleSelector: '.split-thumb',
	resizeWidth: false
});
```
This meant that each of the `.split-thumb` div elements was adding multiple mouseup event handlers. A small change in the code allowed me to use this `handleSelector`:
```
$('.split-top').resizable({
	handleSelector: '+ .split-thumb',
	resizeWidth: false
});
```
Which was nice and clean and feels like it is going with the same sentiment as the `>` extension:
```
function getHandle(selector, $el) {
	if (selector && selector.trim()[0] === ">") {
		selector = selector.trim().replace(/^>\s*/, "");
		return $el.find(selector);
	} else if (selector && selector.trim()[0] === "+") {
		selector = selector.trim().replace(/^\+\s*/, "");
		return $el.parent().find(selector);
	}
	return selector ? $(selector) : $el;
}
```

**Comment by RickStrahl** [comment]
0.26 changes limits the selector syntax to the parent container which should improve things a bit. Check with latest and if there's still an issue please re-open this issue. Thanks.
