### ISSUE TITLE
Mutliple drag handles

### ISSUE THREAD

**Issue by nickberens360** [RickStrahl/jquery-resizable#24]
Greetings, love your plugin and the small footprint! Is it possible to have multiple drag handles like on Google inspect element?
![image](https://user-images.githubusercontent.com/1283934/30595138-f3ca0636-9d15-11e7-8c7e-bfffb93932f9.png)

**Comment by RickStrahl** [comment]
Yes you can specify multiple splitter handles in the jquery selector or you can provide multiple separate commands to  up multiple selectors:

#### Multiple selectors 
```
 $(".panel-left").resizable({
        handleSelector: ".splitter,.splitter2",
        resizeHeight: false
    });
```
in this case both splitter and splitter2 are used for handles. This works only if the drag behavior of both is the same.

If you need separate drag behaviors (ie. one vertical one horizontal), then you need two separate resizables:

```
   // rsize width
   $(".panel-left").resizable({
        handleSelector: ".splitter",
        resizeHeight: false
    });
   // resize height
   $(".panel-left").resizable({
        handleSelector: ".splitter2",
        resizeWidth: false
    });
```
