### ISSUE TITLE
Package.json main property

### ISSUE THREAD

**Issue by ghidello** [RickStrahl/jquery-resizable#3]
After reading your piece about flex layouts (good stuff as usual!!) I tried it in an electron application and I ended up with the following initializations in my html file:

```javascript
var $ = jQuery = require("jquery"); // Electron hack for having the $ variable populated correctly
require("jquery-resizable-dom/dist/jquery-resizable.min.js");
```

Do you think it would be possible to change the package.json main property pointing it directly to the _jquery-resizable.min.js_ so that it would be possible to simply require the package?

**Comment by RickStrahl** [comment]
Ah, thanks. Missed that. Thanks. Fixed
