### ISSUE TITLE
jQuery ~3.3.1 dependency installs second version

### ISSUE THREAD

**Issue by taleteller** [RickStrahl/jquery-resizable#36]
I install your repository using yarn by running

```
yarn add jquery-resizable-dom
```
into my project. While jQuery version 3.4.1 resides inside the `node_modules` folder as the global version. Due to the dependency within your `package.json` it additionally installs a version of jQuery 3.3.1 as `node_modules` within `jquery-resizable-dom`. This in itself wont be an issue, but your plugin registers against the version 3.3.1 when built with `yarn encore`, making it unavailable for the project built against the 3.4.1.

I suggest to change the dependency within `package.json` to either `~3.3` or `>=3.3.1` to avoid such behavior.

**Comment by jasonpenny** [comment]
This plugin also works with old versions of jQuery, like `2.1.4` I am stuck with on an old project.

You can work around this by adding a resolution to package.json, like

```
  "resolutions": {
    "**/jquery": "3.4.1"
  },
```

It would be nice if this package's dependency were relaxed

**Comment by RickStrahl** [comment]
Fixed in the previous update. Thanks.
