### ISSUE TITLE
Add Destroy or Update methods

### ISSUE THREAD

**Issue by ignoreswing** [RickStrahl/jquery-resizable#7]
Dear author,
Thank you for providing this plugin. 
I recently use this plugin in my project while I encountered a problem.
The content of my div can be changed, so I have to re-initialize the plugin.

For example, I wrote the following code

``` javascript
$('#content-view').resizable({
    handleSelector: '.resize-grip',
    onDrag: function(e, $el, newWidth, newHeight) {
        if(newWidth < 100) return false;
    }
});

// After content is changed...
$('#content-view').resizable({
    handleSelector: '.resize-grip',
    onDrag: function(e, $el, newWidth, newHeight) {
        if(newWidth < 500) return false;
    }
});
```

In this case, the new options fail to take effect (struggle with previous options).
What's even worse, `Function startDragging()` will be fired twice.

Currently, I manually unbind the events with the following code before re-initialization,
`$('#content-view .resize-grip').off('mousedown.rsz touchstart.rsz');`
I think that would be great if the plugin can provide a destroy or a update methods for users.

**Comment by RickStrahl** [comment]
destroy handler was added in 0.26
```
$el.resizable("destroy");
```
